### ISSUE TITLE
[EMF resource] Port validation level option from EMC driver

### ISSUE THREAD

**Issue by agarciadom** [epsilonlabs/emc-rdf#42]
We should add an option to `.rdfres` files to do validation in the same style as we do from the EMC driver.

It could look like this:

```yaml
dataModels:
  - model.ttl
schemaModels:
  - schema.ttl
validation:
  mode: jena-valid
```
