### ISSUE TITLE
[EMF resource] Add option for preferred language order

### ISSUE THREAD

**Issue by agarciadom** [epsilonlabs/emc-rdf#43]
We could add an option for a preferred language order to `.rdfres` files, similarly to what we have in the EMC driver. It could look like this:

```yaml
dataModels:
  - model.ttl
schemaModels:
  - schema.ttl
languageOrder:
  - en:GB
  - en
```
